version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3308:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=course_management
    volumes:
    - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
